name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable

      - name: Install python for stub (if not present)
        run: sudo apt-get update && sudo apt-get install -y python3

      - name: Run tests
        env:
          RUST_BACKTRACE: 1
        run: cargo test --tests
